### ISSUE TITLE
date 3.0

### ISSUE THREAD

**Issue by nschloe** [mesonbuild/hinnant-date#3]
date 3.0.0 was released, please update.

**Comment by legeana** [comment]
Pull requests are welcome :)

**Comment by alebastr** [comment]
@legeana could you please initialize branch for 3.0.0? I wanted to create a PR but github restricts PR target to existing branches.

**Comment by legeana** [comment]
You can target master and I will change the branch later. Just don't remove the ability of maintainers to modify pull request.

**Comment by nschloe** [comment]
Has this been accidentally closed or is the issue indeed fixed yet?

**Comment by legeana** [comment]
Accidentally. @alebastr is working on the wrap in https://github.com/mesonbuild/hinnant-date/pull/4.

**Comment by eli-schwartz** [comment]
This was fixed in #4
